SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK AS B 
    JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES AS I ON B.BOOK_ID = I.BOOK_ID
WHERE YEAR(I.SALES_DATE) = 2022 and MONTH(I.SALES_DATE) = 1
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC