SELECT CAR_ID, '대여중' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= DATE('2022-10-16') AND END_DATE >= DATE('2022-10-16')
GROUP BY CAR_ID

UNION
 
SELECT CAR_ID, '대여 가능' AS AVAILABILITY
FROM 
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE > DATE('2022-10-16') OR END_DATE < DATE('2022-10-16')
    GROUP BY CAR_ID
) KK
WHERE CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= DATE('2022-10-16') AND END_DATE >= DATE('2022-10-16')
)

ORDER BY CAR_ID DESC
