SELECT FLAVOR FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) FROM
    (
        SELECT *
        FROM FIRST_HALF
        UNION
        SELECT *
        FROM JULY
    ) UN
    GROUP BY FLAVOR
    ORDER BY SUM(TOTAL_ORDER) DESC
    LIMIT 3
) FT